---
- hosts: web
  name: removing what has been done
  become: yes
  vars:
    httpd_packages:
      - httpd
      - mod_wsgi

  tasks:
    - name: remove httpd packages
      yum:
        name: "{{ item }}"
        state: absent
      with_items: "{{ httpd_packages }}"
      notify: stop httpd service

    - name: stop httpd
      service:
        name: httpd
        state: stopped
        enabled: no
