---
- hosts: web
  name: Install Apache web services
  become: yes

  tasks:
  - name: install apache
    yum:
      name: httpd
      state: present

  - name: start httpd
    service:
      name: httpd
      state: started
